### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by urltalk** [Mews/spotify-lyrics#1]
I got this message

"Failed to execute script 'main' due to unhandled exception: Server listening on localhost has not been accessed

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "gui.py", line 41, in __init__
  File "spotify_client.py", line 15, in create_spotify_client
  File "spotipy\oauth2.py", line 902, in get_access_token
  File "spotipy\oauth2.py", line 843, in get_authorization_code
  File "spotipy\oauth2.py", line 799, in _get_auth_response
  File "spotipy\oauth2.py", line 822, in _get_auth_response_local_server
spotipy.oauth2.SpotifyOauthError: Server listening on localhost has not been accessed"

**Comment by Mews** [comment]
Hi thanks for opening an issue :)
I have exams right now so It might take me a while to address this, but in the meanwhile could answer a few questions about this?
- What operating system are you using?
- What were you doing when this error appeared? (Ex.: When opening the app)
- Were you able to use the app previously?
- Did you configure your spotify app according to [the guide](https://github.com/Mews/spotify-lyrics/blob/main/TUTORIAL.md)?

**Comment by Mews** [comment]
I'm closing this since its inactive, plus this might just be a transient error, but feel free to comment here if anyone else runs into this 👍
